version: "3.9"
services:
  #lucy_webserver:
    #image: nginx:alpine
    #hostname: lucy-webserver
    #ports:
      #- "80:80"
    #volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
    #depends_on:
      #- sid_fastapi
  lucy_test:
    profiles:
      - testing
    image: lucy_core_testing
    build:
      context: .
      dockerfile: dockerfiles/lucy.Dockerfile
      target: testing
    volumes:
      - ./Lucy/lucy:/app/lucy
      - ./Lucy/tests:/app/tests
      - ./Lucy/requirements:/app/requirements
      - ./Lucy/dependency_stubs:/packages
    command: "pytest"

  #lucy_mix:
    #image: lucy_mixtraltogetherai
    #build:
      #context: .
      #dockerfile: dockerfiles/lucy_mixtraltogetherai.Dockerfile
    #env_file:
      #- .env
    #volumes:
      #- ./Lucy/lucy:/packages/lucy
      #- ./LucyMixtralTogetherAIBackend:/app
    #command: "pytest"
  #lucy_fastapi:
    #image: lucy_fastapi
    #hostname: lucy-fastapi
    #build:
      #context: .
      #dockerfile: Dockerfile
    #volumes:
      #- ./Lucy:/packages/Lucy
      #- ./fastapi_test/app:/app/app
    #env_file:
      #- .env
    #environment:
      #POSTGRES_USER: lucy
      #POSTGRES_PASSWORD: lucy
      #POSTGRES_DB: lucy_fastapi
    #depends_on:
      #- lucy_db
  ## TODO: lucy_django
  #lucy_db:
    #image: ankane/pgvector:v0.5.1
    #hostname: lucy-db
    #environment:
      #POSTGRES_USER: lucy
      #POSTGRES_PASSWORD: lucy
      #POSTGRES_DB: postgres
    #volumes:
      #- .data/postgres-data:/var/lib/postgresql/data
  #lucy_langfuse:
    #image: ghcr.io/langfuse/langfuse:latest
    #hostname: lucy-langfuse
    #environment:
      #- DATABASE_URL=postgresql://lucy:lucy@lucy-db:5432/langfuse
      #- NEXTAUTH_URL=http://langfuse.localhost
      #- NEXTAUTH_SECRET=secret
      #- SALT=salt
    #depends_on:
      #- lucy_db
networks:
  default:
    name: lucy