version: "3.9"
services:
  sid_fastapi:
    image: sid_fastapi
    hostname: sid-fastapi
    build:
      context: fastapi_test
      dockerfile: fastapi_test/Dockerfile
    volumes:
      - src:/sid
      - fastapi_test/app:/app
    env_file:
      - .env
    environment:
      POSTGRES_USER: sid
      POSTGRES_PASSWORD: sid
      POSTGRES_DB: sid_fastapi
      PYTHONPATH: /app;/sid;${PYTHONPATH}
    depends_on:
      - sid_db
  # TODO: sid_django
  sid_db:
    image: ankane/pgvector:v0.5.1
    hostname: sid-db
    environment:
      POSTGRES_USER: sid
      POSTGRES_PASSWORD: sid
      POSTGRES_DB: postgres
    volumes:
      - .data/postgres-data:/var/lib/postgresql/data
networks:
  default:
    name: sid